<?php

/**
 * @file
 * Module file for fcrl_harvest_test.
 */

/**
 * Implements hook_harvest_source_types().
 */
function fcrl_harvest_test_harvest_source_types() {
  return array(
    'harvest_test_type' => array(
      'machine_name' => 'harvest_test_type',
      'label' => 'Fcrl Harvest Test Type',
      'cache callback' => 'fcrl_harvest_cache_default',
      'migration class' => 'HarvestMigration',
    ),
    'harvest_another_test_type' => array(
      'machine_name' => 'harvest_another_test_type',
      'label' => 'Fcrl Harvest Another Test Type',
      'cache callback' => 'fcrl_harvest_cache_default',
      'migration class' => 'HarvestMigration',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function fcrl_harvest_test_menu() {
  $items = array();

  $items['fcrl_harvest_test/resources/redirect'] = array(
    'page callback' => 'fcrl_harvest_test_resources_redirect',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Page callabck for 'fcrl_harvest_test/resources/redirect'.
 */
function fcrl_harvest_test_resources_redirect() {
  drupal_goto("https://s3.amazonaws.com/fcrl-default-content-files/files/district_centerpoints_0.csv");
}
